CREATE TABLE `p_liturgical_day_slug_overrides` (
  `slug_ovr` varchar(40) DEFAULT NULL,
  `title_ovr` varchar(240) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `lit_day_id` varchar(64) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'ADV-I-01-1'),
     (NULL,NULL,'ADV-I-01-2'),
     (NULL,NULL,'ADV-I-01-3'),
     (NULL,NULL,'ADV-I-01-4'),
     (NULL,NULL,'ADV-I-01-5'),
     (NULL,NULL,'ADV-I-01-6'),
     (NULL,NULL,'ADV-I-01-7'),
     (NULL,NULL,'ADV-I-02-1'),
     (NULL,NULL,'ADV-I-02-2'),
     (NULL,NULL,'ADV-I-02-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'ADV-I-02-4'),
     (NULL,NULL,'ADV-I-02-5'),
     (NULL,NULL,'ADV-I-02-6'),
     (NULL,NULL,'ADV-I-02-7'),
     (NULL,NULL,'ADV-I-03-1'),
     (NULL,NULL,'ADV-I-03-2'),
     (NULL,NULL,'ADV-I-03-3'),
     (NULL,NULL,'ADV-I-03-4'),
     (NULL,NULL,'ADV-I-03-5'),
     (NULL,NULL,'ADV-I-03-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     ('O-SAPIENTIA','O, Holy Wisdom','ADV-II-00-1'),
     ('O-ADONAI','O, Lord','ADV-II-00-2'),
     ('O-RADIX-JESSE','O, Root of Jesse','ADV-II-00-3'),
     ('O-CLAVIS-DAVID','O, Key of David','ADV-II-00-4'),
     ('O-ORIENS','O, Rising Sun','ADV-II-00-5'),
     ('O-REX-GENTIUM','O, King of the Nations','ADV-II-00-6'),
     ('O-EMMANUEL','O, Emmanuel','ADV-II-00-7'),
     ('DEC24','December 24','ADV-II-00-8'),
     ('NATIVITY','Christmas Day','NAT-DAY-00-0'),
     ('HOLYFAMILY','Holy Family of Jesus, Mary, and Joseph','NAT-IO-01-0');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'NAT-IO-01-1'),
     (NULL,NULL,'NAT-IO-01-2'),
     (NULL,NULL,'NAT-IO-01-3'),
     (NULL,NULL,'NAT-IO-01-4'),
     (NULL,NULL,'NAT-IO-01-5'),
     (NULL,NULL,'NAT-IO-01-6'),
     ('MOTHEROFGOD','Solemnity of Mary, Mother of God','NAT-OCT-02-0'),
     (NULL,'January 2','NAT-PO-02-1'),
     (NULL,'January 3','NAT-PO-02-2'),
     (NULL,'January 4','NAT-PO-02-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,'January 5','NAT-PO-02-4'),
     (NULL,'January 6','NAT-PO-02-5'),
     (NULL,'January 7','NAT-PO-02-6'),
     ('EPIPHANY','Epiphany of the Lord','NAT-EPI-00-0'),
     (NULL,NULL,'NAT-EPI-00-1'),
     (NULL,NULL,'NAT-EPI-00-2'),
     (NULL,NULL,'NAT-EPI-00-3'),
     (NULL,NULL,'NAT-EPI-00-4'),
     (NULL,NULL,'NAT-EPI-00-5'),
     (NULL,NULL,'NAT-EPI-00-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     ('BAPTOFLORD','Baptism of the Lord','NAT-BAPT-01-0'),
     ('CINERUM','Ash Wednesday','TQ-LENT-00-4'),
     ('THU_POST_CIN','Thursday after Ash Wednesday','TQ-LENT-00-5'),
     ('FRI_POST_CIN','Friday after Ash Wednesday','TQ-LENT-00-6'),
     ('SAT_POST_CIN','Saturday after Ash Wednesday','TQ-LENT-00-7'),
     (NULL,NULL,'TQ-LENT-01-1'),
     (NULL,NULL,'TQ-LENT-01-2'),
     (NULL,NULL,'TQ-LENT-01-3'),
     (NULL,NULL,'TQ-LENT-01-4'),
     (NULL,NULL,'TQ-LENT-01-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'TQ-LENT-01-6'),
     (NULL,NULL,'TQ-LENT-01-7'),
     (NULL,NULL,'TQ-LENT-02-1'),
     (NULL,NULL,'TQ-LENT-02-2'),
     (NULL,NULL,'TQ-LENT-02-3'),
     (NULL,NULL,'TQ-LENT-02-4'),
     (NULL,NULL,'TQ-LENT-02-5'),
     (NULL,NULL,'TQ-LENT-02-6'),
     (NULL,NULL,'TQ-LENT-02-7'),
     (NULL,NULL,'TQ-LENT-03-1');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'TQ-LENT-03-2'),
     (NULL,NULL,'TQ-LENT-03-3'),
     (NULL,NULL,'TQ-LENT-03-4'),
     (NULL,NULL,'TQ-LENT-03-5'),
     (NULL,NULL,'TQ-LENT-03-6'),
     (NULL,NULL,'TQ-LENT-03-7'),
     (NULL,NULL,'TQ-LENT-04-1'),
     (NULL,NULL,'TQ-LENT-04-2'),
     (NULL,NULL,'TQ-LENT-04-3'),
     (NULL,NULL,'TQ-LENT-04-4');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'TQ-LENT-04-5'),
     (NULL,NULL,'TQ-LENT-04-6'),
     (NULL,NULL,'TQ-LENT-04-7'),
     (NULL,NULL,'TQ-LENT-05-1'),
     (NULL,NULL,'TQ-LENT-05-2'),
     (NULL,NULL,'TQ-LENT-05-3'),
     (NULL,NULL,'TQ-LENT-05-4'),
     (NULL,NULL,'TQ-LENT-05-5'),
     (NULL,NULL,'TQ-LENT-05-6'),
     (NULL,NULL,'TQ-LENT-05-7');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     ('PALM','Palm Sunday','TQ-HOLYWEEK-00-1'),
     (NULL,NULL,'TQ-HOLYWEEK-00-2'),
     (NULL,NULL,'TQ-HOLYWEEK-00-3'),
     (NULL,NULL,'TQ-HOLYWEEK-00-4'),
     ('HOLYTHUR','Holy Thursday','TQ-HOLYWEEK-00-5'),
     ('GOODFRI','Good Friday','TQ-HOLYWEEK-00-6'),
     ('HOLYSAT','Holy Saturday','TQ-HOLYWEEK-00-7'),
     ('PASCSUN','Sunday of the Resurrection of the Lord','PASC-OCT-01-1'),
     (NULL,NULL,'PASC-OCT-01-2'),
     (NULL,NULL,'PASC-OCT-01-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'PASC-OCT-01-4'),
     (NULL,NULL,'PASC-OCT-01-5'),
     (NULL,NULL,'PASC-OCT-01-6'),
     (NULL,NULL,'PASC-OCT-01-7'),
     ('PASCOCT','Divine Mercy Sunday','PASC-OCT-02-1'),
     (NULL,NULL,'PASC-AD_ASC-02-2'),
     (NULL,NULL,'PASC-AD_ASC-02-3'),
     (NULL,NULL,'PASC-AD_ASC-02-4'),
     (NULL,NULL,'PASC-AD_ASC-02-5'),
     (NULL,NULL,'PASC-AD_ASC-02-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'PASC-AD_ASC-02-7'),
     (NULL,NULL,'PASC-AD_ASC-03-1'),
     (NULL,NULL,'PASC-AD_ASC-03-2'),
     (NULL,NULL,'PASC-AD_ASC-03-3'),
     (NULL,NULL,'PASC-AD_ASC-03-4'),
     (NULL,NULL,'PASC-AD_ASC-03-5'),
     (NULL,NULL,'PASC-AD_ASC-03-6'),
     (NULL,NULL,'PASC-AD_ASC-03-7'),
     (NULL,NULL,'PASC-AD_ASC-04-1'),
     (NULL,NULL,'PASC-AD_ASC-04-2');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'PASC-AD_ASC-04-3'),
     (NULL,NULL,'PASC-AD_ASC-04-4'),
     (NULL,NULL,'PASC-AD_ASC-04-5'),
     (NULL,NULL,'PASC-AD_ASC-04-6'),
     (NULL,NULL,'PASC-AD_ASC-04-7'),
     (NULL,NULL,'PASC-AD_ASC-05-1'),
     (NULL,NULL,'PASC-AD_ASC-05-2'),
     (NULL,NULL,'PASC-AD_ASC-05-3'),
     (NULL,NULL,'PASC-AD_ASC-05-4'),
     (NULL,NULL,'PASC-AD_ASC-05-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'PASC-AD_ASC-05-6'),
     (NULL,NULL,'PASC-AD_ASC-05-7'),
     (NULL,NULL,'PASC-AD_ASC-06-1'),
     (NULL,NULL,'PASC-AD_ASC-06-2'),
     (NULL,NULL,'PASC-AD_ASC-06-3'),
     (NULL,NULL,'PASC-AD_ASC-06-4'),
     (NULL,NULL,'PASC-AD_ASC-06-5'),
     (NULL,NULL,'PASC-AD_ASC-06-6'),
     (NULL,NULL,'PASC-AD_ASC-06-7'),
     (NULL,'Ascension of the Lord','PASC-ASC-06-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,'Friday after the Ascension','PASC-POST_ASC-06-6'),
     (NULL,'Saturday after the Ascension','PASC-POST_ASC-06-7'),
     (NULL,NULL,'PASC-POST_ASC-07-1'),
     (NULL,NULL,'PASC-POST_ASC-07-2'),
     (NULL,NULL,'PASC-POST_ASC-07-3'),
     (NULL,NULL,'PASC-POST_ASC-07-4'),
     (NULL,NULL,'PASC-POST_ASC-07-5'),
     (NULL,NULL,'PASC-POST_ASC-07-6'),
     (NULL,NULL,'PASC-POST_ASC-07-7'),
     (NULL,'Pentecost Sunday','PASC-PENT-08-1');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-01-1'),
     (NULL,NULL,'OT-OT-01-2'),
     (NULL,NULL,'OT-OT-01-3'),
     (NULL,NULL,'OT-OT-01-4'),
     (NULL,NULL,'OT-OT-01-5'),
     (NULL,NULL,'OT-OT-01-6'),
     (NULL,NULL,'OT-OT-01-7'),
     (NULL,NULL,'OT-OT-02-1'),
     (NULL,NULL,'OT-OT-02-2'),
     (NULL,NULL,'OT-OT-02-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-02-4'),
     (NULL,NULL,'OT-OT-02-5'),
     (NULL,NULL,'OT-OT-02-6'),
     (NULL,NULL,'OT-OT-02-7'),
     (NULL,NULL,'OT-OT-03-1'),
     (NULL,NULL,'OT-OT-03-2'),
     (NULL,NULL,'OT-OT-03-3'),
     (NULL,NULL,'OT-OT-03-4'),
     (NULL,NULL,'OT-OT-03-5'),
     (NULL,NULL,'OT-OT-03-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-03-7'),
     (NULL,NULL,'OT-OT-04-1'),
     (NULL,NULL,'OT-OT-04-2'),
     (NULL,NULL,'OT-OT-04-3'),
     (NULL,NULL,'OT-OT-04-4'),
     (NULL,NULL,'OT-OT-04-5'),
     (NULL,NULL,'OT-OT-04-6'),
     (NULL,NULL,'OT-OT-04-7'),
     (NULL,NULL,'OT-OT-05-1'),
     (NULL,NULL,'OT-OT-05-2');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-05-3'),
     (NULL,NULL,'OT-OT-05-4'),
     (NULL,NULL,'OT-OT-05-5'),
     (NULL,NULL,'OT-OT-05-6'),
     (NULL,NULL,'OT-OT-05-7'),
     (NULL,NULL,'OT-OT-06-1'),
     (NULL,NULL,'OT-OT-06-2'),
     (NULL,NULL,'OT-OT-06-3'),
     (NULL,NULL,'OT-OT-06-4'),
     (NULL,NULL,'OT-OT-06-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-06-6'),
     (NULL,NULL,'OT-OT-06-7'),
     (NULL,NULL,'OT-OT-07-1'),
     (NULL,NULL,'OT-OT-07-2'),
     (NULL,NULL,'OT-OT-07-3'),
     (NULL,NULL,'OT-OT-07-4'),
     (NULL,NULL,'OT-OT-07-5'),
     (NULL,NULL,'OT-OT-07-6'),
     (NULL,NULL,'OT-OT-07-7'),
     (NULL,NULL,'OT-OT-08-1');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-08-2'),
     (NULL,NULL,'OT-OT-08-3'),
     (NULL,NULL,'OT-OT-08-4'),
     (NULL,NULL,'OT-OT-08-5'),
     (NULL,NULL,'OT-OT-08-6'),
     (NULL,NULL,'OT-OT-08-7'),
     (NULL,NULL,'OT-OT-09-1'),
     (NULL,NULL,'OT-OT-09-2'),
     (NULL,NULL,'OT-OT-09-3'),
     (NULL,NULL,'OT-OT-09-4');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-09-5'),
     (NULL,NULL,'OT-OT-09-6'),
     (NULL,NULL,'OT-OT-09-7'),
     (NULL,NULL,'OT-OT-10-1'),
     (NULL,NULL,'OT-OT-10-2'),
     (NULL,NULL,'OT-OT-10-3'),
     (NULL,NULL,'OT-OT-10-4'),
     (NULL,NULL,'OT-OT-10-5'),
     (NULL,NULL,'OT-OT-10-6'),
     (NULL,NULL,'OT-OT-10-7');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-11-1'),
     (NULL,NULL,'OT-OT-11-2'),
     (NULL,NULL,'OT-OT-11-3'),
     (NULL,NULL,'OT-OT-11-4'),
     (NULL,NULL,'OT-OT-11-5'),
     (NULL,NULL,'OT-OT-11-6'),
     (NULL,NULL,'OT-OT-11-7'),
     (NULL,NULL,'OT-OT-12-1'),
     (NULL,NULL,'OT-OT-12-2'),
     (NULL,NULL,'OT-OT-12-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-12-4'),
     (NULL,NULL,'OT-OT-12-5'),
     (NULL,NULL,'OT-OT-12-6'),
     (NULL,NULL,'OT-OT-12-7'),
     (NULL,NULL,'OT-OT-13-1'),
     (NULL,NULL,'OT-OT-13-2'),
     (NULL,NULL,'OT-OT-13-3'),
     (NULL,NULL,'OT-OT-13-4'),
     (NULL,NULL,'OT-OT-13-5'),
     (NULL,NULL,'OT-OT-13-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-13-7'),
     (NULL,NULL,'OT-OT-14-1'),
     (NULL,NULL,'OT-OT-14-2'),
     (NULL,NULL,'OT-OT-14-3'),
     (NULL,NULL,'OT-OT-14-4'),
     (NULL,NULL,'OT-OT-14-5'),
     (NULL,NULL,'OT-OT-14-6'),
     (NULL,NULL,'OT-OT-14-7'),
     (NULL,NULL,'OT-OT-15-1'),
     (NULL,NULL,'OT-OT-15-2');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-15-3'),
     (NULL,NULL,'OT-OT-15-4'),
     (NULL,NULL,'OT-OT-15-5'),
     (NULL,NULL,'OT-OT-15-6'),
     (NULL,NULL,'OT-OT-15-7'),
     (NULL,NULL,'OT-OT-16-1'),
     (NULL,NULL,'OT-OT-16-2'),
     (NULL,NULL,'OT-OT-16-3'),
     (NULL,NULL,'OT-OT-16-4'),
     (NULL,NULL,'OT-OT-16-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-16-6'),
     (NULL,NULL,'OT-OT-16-7'),
     (NULL,NULL,'OT-OT-17-1'),
     (NULL,NULL,'OT-OT-17-2'),
     (NULL,NULL,'OT-OT-17-3'),
     (NULL,NULL,'OT-OT-17-4'),
     (NULL,NULL,'OT-OT-17-5'),
     (NULL,NULL,'OT-OT-17-6'),
     (NULL,NULL,'OT-OT-17-7'),
     (NULL,NULL,'OT-OT-18-1');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-18-2'),
     (NULL,NULL,'OT-OT-18-3'),
     (NULL,NULL,'OT-OT-18-4'),
     (NULL,NULL,'OT-OT-18-5'),
     (NULL,NULL,'OT-OT-18-6'),
     (NULL,NULL,'OT-OT-18-7'),
     (NULL,NULL,'OT-OT-19-1'),
     (NULL,NULL,'OT-OT-19-2'),
     (NULL,NULL,'OT-OT-19-3'),
     (NULL,NULL,'OT-OT-19-4');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-19-5'),
     (NULL,NULL,'OT-OT-19-6'),
     (NULL,NULL,'OT-OT-19-7'),
     (NULL,NULL,'OT-OT-20-1'),
     (NULL,NULL,'OT-OT-20-2'),
     (NULL,NULL,'OT-OT-20-3'),
     (NULL,NULL,'OT-OT-20-4'),
     (NULL,NULL,'OT-OT-20-5'),
     (NULL,NULL,'OT-OT-20-6'),
     (NULL,NULL,'OT-OT-20-7');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-21-1'),
     (NULL,NULL,'OT-OT-21-2'),
     (NULL,NULL,'OT-OT-21-3'),
     (NULL,NULL,'OT-OT-21-4'),
     (NULL,NULL,'OT-OT-21-5'),
     (NULL,NULL,'OT-OT-21-6'),
     (NULL,NULL,'OT-OT-21-7'),
     (NULL,NULL,'OT-OT-22-1'),
     (NULL,NULL,'OT-OT-22-2'),
     (NULL,NULL,'OT-OT-22-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-22-4'),
     (NULL,NULL,'OT-OT-22-5'),
     (NULL,NULL,'OT-OT-22-6'),
     (NULL,NULL,'OT-OT-22-7'),
     (NULL,NULL,'OT-OT-23-1'),
     (NULL,NULL,'OT-OT-23-2'),
     (NULL,NULL,'OT-OT-23-3'),
     (NULL,NULL,'OT-OT-23-4'),
     (NULL,NULL,'OT-OT-23-5'),
     (NULL,NULL,'OT-OT-23-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-23-7'),
     (NULL,NULL,'OT-OT-24-1'),
     (NULL,NULL,'OT-OT-24-2'),
     (NULL,NULL,'OT-OT-24-3'),
     (NULL,NULL,'OT-OT-24-4'),
     (NULL,NULL,'OT-OT-24-5'),
     (NULL,NULL,'OT-OT-24-6'),
     (NULL,NULL,'OT-OT-24-7'),
     (NULL,NULL,'OT-OT-25-1'),
     (NULL,NULL,'OT-OT-25-2');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-25-3'),
     (NULL,NULL,'OT-OT-25-4'),
     (NULL,NULL,'OT-OT-25-5'),
     (NULL,NULL,'OT-OT-25-6'),
     (NULL,NULL,'OT-OT-25-7'),
     (NULL,NULL,'OT-OT-26-1'),
     (NULL,NULL,'OT-OT-26-2'),
     (NULL,NULL,'OT-OT-26-3'),
     (NULL,NULL,'OT-OT-26-4'),
     (NULL,NULL,'OT-OT-26-5');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-26-6'),
     (NULL,NULL,'OT-OT-26-7'),
     (NULL,NULL,'OT-OT-27-1'),
     (NULL,NULL,'OT-OT-27-2'),
     (NULL,NULL,'OT-OT-27-3'),
     (NULL,NULL,'OT-OT-27-4'),
     (NULL,NULL,'OT-OT-27-5'),
     (NULL,NULL,'OT-OT-27-6'),
     (NULL,NULL,'OT-OT-27-7'),
     (NULL,NULL,'OT-OT-28-1');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-28-2'),
     (NULL,NULL,'OT-OT-28-3'),
     (NULL,NULL,'OT-OT-28-4'),
     (NULL,NULL,'OT-OT-28-5'),
     (NULL,NULL,'OT-OT-28-6'),
     (NULL,NULL,'OT-OT-28-7'),
     (NULL,NULL,'OT-OT-29-1'),
     (NULL,NULL,'OT-OT-29-2'),
     (NULL,NULL,'OT-OT-29-3'),
     (NULL,NULL,'OT-OT-29-4');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-29-5'),
     (NULL,NULL,'OT-OT-29-6'),
     (NULL,NULL,'OT-OT-29-7'),
     (NULL,NULL,'OT-OT-30-1'),
     (NULL,NULL,'OT-OT-30-2'),
     (NULL,NULL,'OT-OT-30-3'),
     (NULL,NULL,'OT-OT-30-4'),
     (NULL,NULL,'OT-OT-30-5'),
     (NULL,NULL,'OT-OT-30-6'),
     (NULL,NULL,'OT-OT-30-7');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-31-1'),
     (NULL,NULL,'OT-OT-31-2'),
     (NULL,NULL,'OT-OT-31-3'),
     (NULL,NULL,'OT-OT-31-4'),
     (NULL,NULL,'OT-OT-31-5'),
     (NULL,NULL,'OT-OT-31-6'),
     (NULL,NULL,'OT-OT-31-7'),
     (NULL,NULL,'OT-OT-32-1'),
     (NULL,NULL,'OT-OT-32-2'),
     (NULL,NULL,'OT-OT-32-3');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-32-4'),
     (NULL,NULL,'OT-OT-32-5'),
     (NULL,NULL,'OT-OT-32-6'),
     (NULL,NULL,'OT-OT-32-7'),
     (NULL,NULL,'OT-OT-33-1'),
     (NULL,NULL,'OT-OT-33-2'),
     (NULL,NULL,'OT-OT-33-3'),
     (NULL,NULL,'OT-OT-33-4'),
     (NULL,NULL,'OT-OT-33-5'),
     (NULL,NULL,'OT-OT-33-6');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     (NULL,NULL,'OT-OT-33-7'),
     (NULL,NULL,'OT-OT-34-1'),
     (NULL,NULL,'OT-OT-34-2'),
     (NULL,NULL,'OT-OT-34-3'),
     (NULL,NULL,'OT-OT-34-4'),
     (NULL,NULL,'OT-OT-34-5'),
     (NULL,NULL,'OT-OT-34-6'),
     (NULL,NULL,'OT-OT-34-7'),
     ('TRINITY','Trinity Sunday','OT-FOL-00-1'),
     ('CORPUS','Most Holy Body and Blood of Christ','OT-FOL-00-2');
INSERT INTO liturgio.p_liturgical_day_slug_overrides (slug_ovr,title_ovr,lit_day_id) VALUES
     ('SACREDHEART','Most Sacred Heard of Jesus','OT-FOL-00-3'),
     ('CHRISTTHEKING','Our Lord Jesus Christ, King of the Universe','OT-FOL-00-4'),
     (NULL,'Second Sunday of Christmas','NAT-PO-02-0');
